Motor issues: The following bugs, which affect move completion and signalling in AMControl.h/AMControl.cpp, have been fixed:
AMPVControl (no status)
========================
0 - movingChanged() was never emitted for AMPVControl.  It's supposed to accompany all changes in isMoving(), but it doesn't.  (NOTE that according to the definition of isMoving() for AMPVControls, you'll only see this signal when one of YOUR commanded moves starts and stops. We have no way to determine whenever the control is effectively moving (or moved by others) in real life.)

Resolution: fixed.

1 - If a motor hasn't reached tolerance within the timeout... it reports move failed (even though the motor might still be moving).  This is expected behaviour, since we have no moving status feedback. Suggested feature improvement: should we be looking to see if the position values are still changing? If they are, then we could assume that it's still moving...

Exception: some controls will keep changing continuously; for example, if they have really sensitive or noisy encoders. (ex: REIXS mono feedback) Then what? Are they always reporting isMoving()?

(Question: Should we introduce a concept of minimum significant velocity / minimum significant change between successive monitor events?)

Resolution: Not changing anything for now.

2 - If moving to __where you already are__, no monitors change, therefore moveSucceeded was not issued until we hit the move timeout.  This is a waste of time if you're waiting for a moveSucceeded().
Clarification: what does moveSucceeded actually mean?  (In our mind, it means you reached your target setpoint with enough accuracy, and you're ok to carry on with your experiment.)  Therefore, if a feedback position is within tolerance at the start of a move, we should issue moveSucceeded right away.
EXCEPTION: if tolerance is set to AMCONTROL_TOLERANCE_DONT_CARE (default), then moveSucceeded would always be issued immediately. That's probably not what you want.  So we won't offer this functionality if tolerance() is left at AMCONTROL_TOLERANCE_DONT_CARE.

Resolution: fixed, with exception as described

AMPVwStatusControl
===================
0 - If moving to __where you already are__, no monitors change, therefore moveSucceeded was not issued until we hit the move timeout.  This is a waste of time if you're waiting for a moveSucceeded().
Clarification: what does moveSucceeded actually mean?  (In our mind, it means you reached your target setpoint with enough accuracy, and you're ok to carry on with your experiment.)  Therefore, if a feedback position is within tolerance at the start of a move, we should issue moveSucceeded right away.  EXCEPTION: if tolerance is set to AMCONTROL_TOLERANCE_DONT_CARE (default), then moveSucceeded would always be issued right away. That's probably not what you want.  So we won't offer this functionality if tolerance() is left at AMCONTROL_TOLERANCE_DONT_CARE.

Resolution: fixed, with exception as described